package extract.cli

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

class RunnerTest {
    @Test
    fun defaults() {
        doTest(listOf(), Options())
    }

    @Test
    fun help() {
        doTest(listOf("-help"), Options(help = true))
        doTest(listOf("-help=true"), Options(help = true), errorMessage = "No argument is allowed: true")
        doTest(listOf("-n", "-help"), Options(help = true), errorMessage = "\"-help\" is not a valid value for \"-n\"")
        doTest(listOf("-help", "-n"), Options(help = true), errorMessage = "Option \"-number (-n)\" takes an operand")
    }

    @Test
    fun number() {
        doTest(listOf("-number=30"), Options(number = 30))
        doTest(listOf("-n=25"), Options(number = 25))
        doTest(listOf("-number", "5"), Options(number = 5))
        doTest(listOf("-n", "6"), Options(number = 6))
        doTest(listOf("-n", "6.21"), Options(number = 6), errorMessage = "\"6.21\" is not a valid value for \"-n\"")
    }

    fun doTest(args: List<String>, expectedOptions: Options, errorMessage: String? = null) {
        val optionsCheck = {
            val options = Runner.parseArguments(args.toTypedArray())
            Assertions.assertEquals(expectedOptions, options)
        }

        try {
            val (options, _) = Runner.parseArguments(args.toTypedArray())
            Assertions.assertEquals(expectedOptions, options)

            if (errorMessage != null) {
                Assertions.fail<Any>("Parse error was expected")
            }
        } catch (ex: ParserException) {
            if (errorMessage == null) {
                throw ex
            }

            Assertions.assertEquals(errorMessage, ex.message, "Bad parse error")
            Assertions.assertEquals(USAGE, ex.usage.replace("\r", ""), "Bad usage")
        }
    }

    companion object {
        val USAGE = """
             | -extracts (-f) FILE : Path to extracts file. "repository/.extracts" path is
             |                       used by default.
             | -help               : Get the program options help
             | -html-log FILE      : Output html file. "extracts.html" in working directory
             |                       will be generated by default.
             | -number (-n) N      : Limit the number of commits to output. Default is 50.
             | -open               : Is result history should be open automatically. Default
             |                       is TRUE.
             |
            """.trimMargin()
    }
}
